all: Problem1_1 Problem1_2 Problem2

Problem1_1: Problem1_1.c
	gcc Problem1_1.c -o Problem1_1 -lpthread

Problem1_2: Problem1_2.c
	gcc Problem1_2.c -o Problem1_2 -lpthread

Problem2: Problem2.c
	gcc Problem2.c -o Problem2 -lpthread -lm

clean:
	rm Problem1_1 Problem1_2 Problem2
