all: Problem0_A Problem0_B Problem0_C Problem2  Problem3 Problem4

Problem0_A: Problem0_A.c
	gcc Problem0_A.c -g -o Problem0_A

Problem0_B: Problem0_B.c
	gcc Problem0_B.c -g -o Problem0_B

Problem0_C: Problem0_C.c
	gcc Problem0_C.c -g -o Problem0_C

Problem2: Problem2.c
	gcc Problem2.c -g -o Problem2

Problem3: Problem3.c
	gcc Problem3.c -g -o Problem3

Problem4: Problem4.c
	gcc Problem4.c -g -o Problem4

clean:
	rm Problem0_A Problem0_B Problem0_C Problem2 Problem4


